HubSpot/hubspot-php

src/HubSpotService.php

I've added the ability to use your own HttpClient as discussed.
This will open up the library for developers to use any HTTP client and are not bound to Guzzle

Added the ability to use your own HttpClient implementation

---

src/Api/Api.php

Base URL was still broken in this branch and request was moaning about required 3rd parameter so I re-added the default empty array back in

Fixed the baseUrl property and added default value for Api::request

---

src/Api/Companies.php
tests/integration/Api/CompaniesTest.php
tests/spec/Api/CompaniesSpec.php

- getRecentlyModified
- getRecentlyCreated
- getAssociatedContacts
- getAssociatedContactIds
Were missing additional pagination parameters. I also commented back couple of assertions. The hubspot API seems to randomly produce the errors, not the tests?

Add additional pagination parameters to some company endpoints

---

src/Api/Forms.php
tests/integration/Api/FormsTest.php

Guzzle v6 requires to use 'form_params' instead of 'body' in options

---

src/Api/Workflows.php

Workflow enrollment was using GET instead of POST, as per hubspot documentation: http://developers.hubspot.com/docs/methods/workflows/add_contact

Fix workflow enrollment using incorrect HTTP verb

---

tests/integration/Api/CompaniesTest.php

Tests assumed that there is a company associated with `example.com` domain, but it was not.
Fixed it by adding domain during company creation.

Fixed tests for companies endpoints

---

src/Resources/Files.php

Change the Files::all() method to use a query string for options instead of a JSON body.

Fix Files all request to match expected format

---

src/Resources/Engagements.php

Add undocumented API feature to add attachments to engagements.
See: http://integrate.hubspot.com/t/attaching-file-to-company/154/8

Add Attachment functionality to engagements

---

src/Factory.php
src/Resources/SingleEmail.php

Adds support for the Single Send API (part of the Transactional Email Add-on – http://developers.hubspot.com/docs/methods/email/transactional_email/single-send-overview)

Single Send API Support

---

README.md
src/Factory.php
src/Http/Client.php
src/Resources/Timeline.php
tests/integration/Resources/TimelineTest.php

This PR adds support for the Timeline API!
🎉

Timeline API

---

src/Resources/Timeline.php

This PR adds support for sending custom event type data in Timeline events. As you can see, there was already support for `extraData`, but `extraData` isn't segment-able on Timeline events like custom event type data is.
If you take a look at section 4 (http://developers.hubspot.com/docs/methods/timeline/timeline-overview) "Creating an Event" there's an example that shows custom data in the JSON body directly:
```bash
curl -X PUT -H "Content-Type: application/json" -d '
{
"id": "001-001001",
"eventTypeId": <<eventTypeId>>,
"webinarName": "A Test Webinar",
"webinarId": "001001",
"email": "a.test.contact@email.com"
}' \
https://api.hubapi.com/integrations/v1/<<applicationId>>/timeline/event?access_token=<<OAuthAccessToken>>
```

Add support for event type data in Timeline events.

---

src/Http/Client.php

Recently, HubSpot rolled out their new authentication which is OAuth2. OAuth1 is still currently supported, and will be for quite some time since they're just now making the transition (I sent an email asking someone about that and got that confirmation), so both forms of OAuth should be supported.
http://developers.hubspot.com/docs/methods/oauth2/oauth2-overview
As mentioned in #50, I don't think this library should have anything to do with generating the access tokens or refreshing them, but just another way to sign the request. The difference here is that instead of signing requests `?access_token=token` we now sign them with an [Authorization header](http://developers.hubspot.com/docs/methods/oauth2/using-access-tokens):
```
Authorization: Bearer {token}
```

OAuth2 support

---

src/Http/Client.php
src/Resources/Forms.php

There's an issue when doing form submissions, it will send the API credentials as a query string, and HubSpot actually does not filter this out. This is a pretty big security risk, so I figured I'd help out and fix it.

Preventing form submission to send API key details

---

README.md
src/Factory.php
src/Http/Client.php

With this change, it is now possible to set options to be passed
with the request method on a per callee level. Each client creation
is able to accept options, that will be applied to each call to
any request function and be respected by Guzzle Requests.
The default behaviour will be as before that change.
Additionally, the exception handling and the Response wrapping
into a SevenShores\Hubspot\Http\Response object can be avoided.
So it is possible to care for the error handling in the own
application.
Again, the default behaviour remains unchanged, the response
is wrapped and SevenShores\Hubspot\Exceptions are thrown.

[FEATURE] Allow passing of request options and own error handling

---

src/Http/Client.php

Guzzle truncates Exception->getMessage(). Use \GuzzleHttp\Psr7\str($e->getResponse()) instead.

Get full error message

---

src/Resources/Contacts.php
tests/integration/Resources/ContactsTest.php

Add support for updateByEmail to the Contact resource

---

src/Resources/Engagements.php

The missing endpoint engagements/associated was added [http://developers.hubspot.com/docs/methods/engagements/get_associated_engagements](url)

Added Associated

---

src/Resources/Events.php

The Hubspot Event API seems to be called slightly differently than other HS API endpoints. All parameters to the endpoint are in the querystring, whereas it seems other endpoints (contact: _/contacts/v1/contact/vid/:contact_id/profile_) take parameters as part of the URL, and then optional querystring parameters.
Currently, calling this class `$hubspot->events()->trigger('123', '12345', 'test@example.com');` (psuedo-code) with in this manner results in a request to:
```
http://track.hubspot.com/v1/event?_a=123&_n=12345?email=test@example.com
```
_Note the two "?"_
Anyways, this results in a 200 status code, it just records the events incorrectly on the hubspot side, so I can't even update the tests for this PR. This PR changes the events call to add all parameters to the querystring, and …

Correctly call Events API.

---

src/Resources/Contacts.php

As describe here [https://developers.hubspot.com/docs/methods/contacts/get_contact_by_email](https://developers.hubspot.com/docs/methods/contacts/get_contact_by_email) we can also pass optional param to filter results.

Add optional param to Contacts getByEmail function

---

src/Resources/Files.php

Fixed parameter name, as per https://developers.hubspot.com/docs/methods/files/post_folders
There's one error in unit test but unrelated to this fix.
```1) SevenShores\Hubspot\Tests\Integration\Resources\TimelineTest::createOrUpdateBatch
SevenShores\Hubspot\Exceptions\BadRequest: HTTP/1.1 403 Forbidden
Access-Control-Allow-Credentials: false
Content-Type: application/json; charset=UTF-8
Content-Length: 175
Date: Fri, 22 Sep 2017 15:40:25 GMT
Connection: close
{"status":"error","message":"You don't have access to this application.","correlationId":"0bbc3531-c8a3-43ec-ba83-5a1f466c7e25","requestId":"f81c130efac5229c405be6176729162a"}```

Fixed parameter name for createFolder()

---

README.md

I just started to play around this lib, and it seems like the documentation isnt acurate.
Update documentation about Guzzle option "http_errors" as of http://docs.guzzlephp.org/en/latest/request-options.html#http-errors

Fix documentation regarding HTTP exceptions

---

src/Resources/Companies.php
tests/integration/Resources/CompaniesTest.php

The old endpoint GET company->getByDomain is deprecated.
See new endpoint documentation: https://developers.hubspot.com/docs/methods/companies/search_companies_by_domain
Resolves: #127

[FEATURE] New endpoint for company->searchByDomain

---

src/Resources/Files.php

The folders API call should be in this format. The way it was the options where never being used.

Fix folders

---

src/Resources/Files.php

Includes the previous API fix for folders as well as an update to the files replace function where Guzzle was warning about the deprecated use of "body" to send the file data.

API fix for folders as well as Guzzle warnings for file replace

---

src/Resources/Engagements.php
src/Resources/Files.php

When calling the engagements/associated API the params for offset and limit should be able to be specified.

The associated API call should allow offset and limit

---

src/Resources/Contacts.php
tests/integration/Resources/ContactsTest.php

as per api docs;
https://developers.hubspot.com/docs/methods/contacts/batch_create_or_update
has optional parameter Change Source (&auditId)

Allow optional params for contacts batch create/update

---

src/Resources/Pages.php
tests/integration/Resources/BlogPostsTest.php
tests/integration/Resources/PagesTest.php

Found a bug in both the test and implementation of cloning pages/blog posts.
This PR fixes both issues.

Fixing bug in cloning pages/posts endpoint

---

src/Factory.php
src/Resources/EcommerceBridge.php
tests/integration/Resources/EcommerceBridgeTest.php

Hello! 👋 
I've added support for the new [ECommerce Bridge API](https://developers.hubspot.com/docs/methods/ecomm-bridge/ecomm-bridge-overview). Based on #140 and weird API inconsistencies with the `demo` api key, I wasn't sure how comprehensive to make the unit tests. However, I have included some tests for the endpoints that were working consistently for me.
Let me know if there's anything you'd like to change. Thanks!

Adding support for ECommerce Bridge API

---

src/Resources/Contacts.php

The recent method looks for recently updated and created contacts.
So I added the endpoint for recently created contacts. I called the method recentNew.

Added missing Contact endpoint

---

src/Resources/HubDB.php

Breaking bug where Hubspot throws 405 method not allowed error.

Bugfix where wrong HTTP verb was used to update table row in HubDB

---

src/Resources/Webhooks.php

Just changing the domain endpoint from QA to productions domains in Resources\Webhooks settings methods

BUGFIX: Resources\Webhooks | api.hubapiqa > api.hubapi

---

src/Resources/Deals.php
tests/integration/Resources/DealsTest.php

Created an endpoint allowing batch updates for deals. See:
https://developers.hubspot.com/docs/methods/deals/batch-update-deals
Tests are also included. The `delete` test in `tests/integration/Resources/DealTest` was failing in my case. But not due to my additions. I believe `getById` is throwing an exception because the deleted record isn't found (as it should be), causing the test to fail though. When I remove [these lines](https://github.com/ryanwinchester/hubspot-php/blob/0b42c86174f5cd54b0c2609814a3eee322363c6b/tests/integration/Resources/DealsTest.php#L134-L135) all deal tests pass.

Create endpoint for batch-updating deals

---

src/Resources/Engagements.php

Add `method` argument in `update` engagement in order to use `patch` instead of `put`.
https://developers.hubspot.com/docs/methods/engagements/update_engagement-patch

add method argument in update engagement

---

src/Resources/Tickets.php

The Tickets API supports optional parameters when getting by ID, [documented here](https://developers.hubspot.com/docs/methods/tickets/get_ticket_by_id), which the Tickets resource doesn't support.
This PR adds in an optional $params parameter to the Tickets::getById so we can actually use the query string for this call.

Add optional $params to Tickets::getById

---

src/Http/Client.php

A server error (HTTP 50x) is now thrown as a BadRequest exception, which
is semantically incorrect and makes it impossible to distinguish between
faulty requests and responses.

Distinguish server and client errors

---

src/Factory.php

I've previously used the implicitly public `$client` property from the `Factory` class to create helpers for APIs this library currently doesn't support, like [CRM Pipelines](https://developers.hubspot.com/docs/methods/pipelines/pipelines_overview), the change made in #219 broke my helpers which were using the `$client` property, hence this PR to expose the property via a getter instead.

Expose Factory::$client property through getter

---

src/Exceptions/BadRequest.php
src/Exceptions/HubspotException.php
src/Http/Client.php
tests/unit/Exception/HubspotExceptionTest.php

Closes #88 
I've also added tests to cover the new logic :)

fix: remove API keys from error messages

---

.travis.yml
phpunit.xml

Noticed that travis was only running on PHP versions that are already.
https://www.php.net/supported-versions.php
As such, I've added all of the supported versions as well as configuring the cache to speed up the builds.
I also swapped the install command to use `dist` instead of source. IMO in CI it should match how people will be using the package (composer will instal from dist by default)

fix: ci improvements

---

src/helpers.php
tests/unit/Support/QueryBuilderTest.php

Hi, I saw in several place in Hubspot doc when you use `optional query string options` the value needed is 'true'.
you can see it [here](https://developers.hubspot.com/docs/methods/files/post_files) for parameters `overwrite` and `hidden`.
When I read it for me 'true' is a boolean, but when you use a param with `true` the query_string_options convert it into integer.
So instead of have `hidden=true` I have `hidden=1` and this doesn't work with Hubspot API.
I make an update in `query_string_options` in case of a boolean is passed in the query, the return should be  `true` instead of 1.
What do you think ?
Thanks

[Helpers] add check on bool type when build query string

---

README.md

Adds a quick intro and links to the Hubspot documentation about API keys and tokens. While not absolutely necessary, these make the README.md a stronger resource for the newcomer.

Adds info and links to the README.md

---

src/Resources/ContactLists.php

The endpoint to remove contacts from a list will also support an array of emails being passed through. This changes the removeContact signature to match the addContact signature by adding an optional 3rd parameter to the removeContact method so that users may be removed from a list by email address.
Closes #317.

Add support for removing list contacts by email address

---

src/Resources/Pages.php

The updateAutoSaveBuffer function of the pages ressources is not sending the params when calling the endpoint. So no data is sent to be save to the page buffer.
https://developers.hubspot.com/docs/methods/pages/put_pages_page_id_buffer

Add params to updateAutoSaveBuffer

---

src/Resources/Contacts.php
tests/Integration/Resources/ContactsTest.php

Hubspot API supports deleting & adding secondary email addresses, but the library doesnt have those methods. 
https://legacydocs.hubspot.com/docs/methods/contacts/add-a-secondary-email-address
https://legacydocs.hubspot.com/docs/methods/contacts/delete-a-secondary-email-address
This PR simply adds those methods with their corresponding tests.

Add support for adding/deleting secondary email addresses API

---

src/Http/Response.php

We got the following message in our project when upgrading to `php8.1`, this PR will fix these deprecation warnings
```
PHP Deprecated:  Return type of SevenShores\Hubspot\Http\Response::offsetExists($offset) 
should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the 
#[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in 
/srv/backend/vendor/hubspot/hubspot-php/src/Http/Response.php on line 65
```
```
PHP Deprecated:  Return type of SevenShores\Hubspot\Http\Response::offsetGet($offset)
should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the
#[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in
/srv/backend/vendor/hubspot/hubspot-php/src/Http/Response.php on line …
```

fix php8.1 deprecated message

---

README.md

The `oauth2` config is [treated as a boolean](https://github.com/HubSpot/hubspot-php/blob/master/src/Http/Client.php#L68). If someone copies and pastes this example they will get unexpected behavior because `'false'` evaluates to `true` if converted to a boolean.
```
php > $oauth = 'false';
php > var_dump(isset($oauth) ? $oauth : false);
string(5) "false"
php > var_dump((bool)$oauth);
bool(true)
```

README: Fix Config Example

---

src/RetryMiddlewareFactory.php

```
SevenShores\Hubspot\RetryMiddlewareFactory::SevenShores\Hubspot\{closure}():
Argument #4 ($exception) must be of type ?GuzzleHttp\Exception\RequestException, TypeError given,
called in /var/task/vendor/guzzlehttp/guzzle/src/RetryMiddleware.php on line 99
```
I periodically see this error, assumingly from `json_decode()` failing on the response body from a server error message like a gateway timeout or network connection lost.
This package's Closure functions passed into `GuzzleHttp\Middleware::retry()` define its 4th argument as `RequestException $exception = null` when the callback can receive other exceptions, which will cause another cascading exception from a method signature mismatch. Class `GuzzleHttp\RetryMiddleware` doesn't apply such typehinting to its `$reason` variable: …

Fix exceptions from `RetryMiddlewareFactory` callback method signature mismatch

---

src/Http/Response.php

Following on from https://github.com/HubSpot/hubspot-php/issues/383 there are a few more missing return types in the `SevenShores\Hubspot\Http\Response` class.

Add PHP 8.1 return types to the Response class

---

composer.json

See https://www.php-fig.org/psr/psr-7/meta/#72-type-additions
It looks like this package is already compatible with the new type annotations: https://github.com/HubSpot/hubspot-php/commit/ef7e73e5e872edde487d7587b2cd9ecc2297832b
However, composer.json only declares compatibility with version 1.1.

Support psr/http-message:^2.0
