src/Api/Contacts.php
The all function takes as a parameter vidOffset so I have updated the comment to correct this
=> Corrected documentation

src/Api/Contacts.php
See example URL on http://developers.hubspot.com/docs/methods/contacts/get_batch_by_email
=> Fixed endpoint/URL for Contacts::getBatchByEmails()

README.md, spec/Fungku/HubSpot/HubSpotServiceSpec.php, src/Api/Events.php, src/HubSpotService.php
The HubSpot documentation for this is at: https://developers.hubspot.com/docs/methods/enterprise_events/http_api
=> Add support for the events API.

.travis.yml
See http://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F
=> Use Travis' new container-based infrastructure.

src/Api/ContactLists.php
The feature existed on Contacts, I've just ported that across to the ContactLists::contacts method
=> Added the feature to specify properties to ContactLists::contacts

README.md, composer.json, phpunit.xml, src/Api/Companies.php, tests/Helpers/SendsRequests.php, tests/integration/Api/CompaniesTest.php, tests/spec/Api/CompaniesSpec.php
Some help with the issue #11 :).
=> Added Companies endpoints

README.md, src/Api/CompanyProperties.php, src/HubSpotService.php, tests/integration/Api/CompanyPropertiesTest.php, tests/spec/Api/CompanyPropertiesSpec.php, tests/spec/HubSpotServiceSpec.php
Help with #11 :).
The keyword integration tests seem to be failing for me, but its probably because of the API? I'm getting 401 statusCode.
=> Add company properties endpoint

.gitignore, composer.json, src/Api/Engagements.php, tests/integration/Api/EngagementsTest.php
I follow your rules to implement all the engagements part, including:
+ create
+ update
+ delete 
+ get 
+ associate
Reference for: http://developers.hubspot.com/docs
=> Add engagements service

src/Api/Deals.php, tests/integration/Api/CompaniesTest.php, tests/integration/Api/DealsTest.php
Deals feature (http://developers.hubspot.com/docs/methods/deals/deals_overview)
- create
- update
- delete
- recently created
- recently modified
- associate with company
- disassociate from company
- associate with contact
- disassociate from contact
=> Deals feature

src/Api/Owners.php, src/HubSpotService.php, tests/integration/Api/OwnersTest.php
Owners endpoints (http://developers.hubspot.com/docs/methods/owners/get_owners)
- create
- update
- find by id
- find all
=> Owner endpoints

src/Api/BlogTopics.php, src/HubSpotService.php
This is for the v3 api. Hope you can accept.
http://developers.hubspot.com/docs/methods/blog/v3/list-blog-topics
=> API call for blog topics added

README.md, src/Api/BlogAuthors.php, src/HubSpotService.php, tests/Helpers/SendsRequests.php, tests/integration/Api/BlogAuthorsTest.php, tests/integration/Api/BlogTopicsTest.php, tests/spec/Api/BlogAuthorsSpec.php, tests/spec/Api/BlogTopicsSpec.php, tests/spec/HubSpotServiceSpec.php
This closes #45 
Please @ryanwinchester accept this endpoint (http://developers.hubspot.com/docs/methods/blog/v3/list-blog-authors)
=> Added blog authors (COS) for api v3

src/Resources/DealProperties.php
A start of the deal properties entity. I've only added the methods I've needed for now, but it's a start.
=> Start DealProperties

src/Resources/Files.php
HubSpot expects a multipart form for uploading files.
=> Fix Files upload to use multipart upload

src/Factory.php
This just updates the comment in the factory so that IDE's can figure out what's going on from the factory.
=> Added missing resources as a factory method for IDE awareness

src/Resources/Companies.php, tests/integration/Resources/CompaniesTest.php, tests/spec/Resources/CompaniesSpec.php
This allows us to get "ALL" companies in a paged manner.
=> Added method to get all companies

src/Resources/Engagements.php
=> Added method to retrieve all engagements

src/Factory.php, src/Resources/DealPipelines.php, tests/integration/Resources/DealPipelinesTest.php
Hi, I made a pipelines API. The tests are tricky, because they rely on the current state of the demo sandbox delivered by hubspot. I hope it helps anyway.
=> [FEATURE] Add pipelines API

src/Http/Client.php
This fixed the bug in #81 for me.
=> Removed use guzzle response to use the hubspot-php response instead

src/Resources/Deals.php
Created the method associateWithContact to get all deals associated with a specific client VID
=> Get all deals associated with a specific client

src/Resources/Deals.php, tests/integration/Resources/DealsTest.php
This method let you get all deals paged
=> New method for get all deals paged

src/Resources/DealProperties.php, tests/integration/Resources/DealPropertiesTest.php, tests/spec/Resources/DealPropertiesSpec.php
Enable to create a deal property
https://developers.hubspot.com/docs/methods/deals/create_deal_property
=> Create a deal property

src/Resources/Deals.php, tests/integration/Resources/DealsTest.php
The Deals API missed the function getAssociatedDeals.
=> [FEATURE] Add deals endpoint 'getAssociatedDeals'

src/Resources/DealProperties.php, tests/integration/Resources/DealPropertiesTest.php
Add missing functions to deal with deal property groups.
=> [FEATURE] Provide Deal property group methods

src/Resources/OAuth2.php
Supports authorize link generation, access token management / refresh / token info
=> Added new resource that can do a full integration with OAuth 2.0

src/Resources/ContactLists.php, tests/integration/Resources/ContactListsTest.php
as is allowed by the hubspot API
https://developers.hubspot.com/docs/methods/lists/add_contact_to_list
Added a test as well for it.
=> Updated ContactList::addContact to allow contact id or email

src/Resources/Events.php
=> Remove auth from event trigger.

src/Resources/Contacts.php
Add contact merge support, https://developers.hubspot.com/docs/methods/contacts/merge-contacts.
=> Add contact merge support

src/Factory.php, src/Resources/Integration.php, tests/integration/Resources/IntegrationTest.php
https://developers.hubspot.com/docs/methods/check-daily-api-usage
=> Support for method "Check daily API usage"

src/Resources/Companies.php, tests/integration/Resources/CompaniesTest.php
Implementation of method Update a group of companies
https://developers.hubspot.com/docs/methods/companies/batch-update-companies
=> Implement batch update of companies

src/Resources/Engagements.php
This is an undocumented API but it might come in handy for other users of this wrapper?
=> API to fetch activity types for hubs on Professional plans

src/Resources/Integration.php
=> Support Account Details endpoint

src/Resources/Comments.php
Basic setup for listing Blog Comments
=> add listing of Blog Comments

src/Resources/Forms.php
Includes $parms array for the limit and after fields
Fixes #176
=> Added getSubmissions endpoint

src/Factory.php
The __call method on Factory.php was not compatible with Mockery.
=> Updated Factory.php

README.md, src/Resources/CrmPipelines.php, tests/integration/Resources/CrmPipelinesTest.php
- Adding CRUD endpoints for CRM Pipelines API
- Adding related integration tests
- Updating README.md with new feature
- Resolves #170
=> CRM Pipelines

src/Resources/Engagements.php, tests/integration/Resources/EngagementsTest.php
- Adding an endpoint for getting call dispositions
- Adding related test
- Resolves #145
=> Engagements API - Get Call Dispositions

src/Resources/OAuth2.php
Not sure if I missed it earlier or a merge conflict gone wrong..
=> Incorrect default value for OAuth2 getTokensByCode

src/Resources/Forms.php
https://github.com/HubSpot/hubspot-php/issues/235
=> added get method

src/Resources/EcommerceBridge.php, src/Resources/Files.php, tests/integration/Resources/EcommerceBridgeTest.php
https://github.com/HubSpot/hubspot-php/issues/237
=> added batch file upload method

src/Resources/Timeline.php
https://developers.hubspot.com/docs/methods/timeline/get-event
=> add get method

src/Factory.php
=> fix: add missing crm pipelines docblock to factory

src/Exceptions/HubspotException.php, src/Resources/HubDB.php, tests/unit/Exception/HubspotExceptionTest.php
https://github.com/HubSpot/hubspot-php/issues/281
=> add name and path to hubDB

README.md
I was setting up the SDK today and I encountered a couple of mistakes.
=> Couple of fixes to the README

README.md
Fixes https://github.com/HubSpot/hubspot-php/issues/342
=> Fix README samples

README.md
for resolving https://github.com/HubSpot/hubspot-php/issues/320
=> add an example of calling a resource

.gitignore, phpunit.xml, tests/Integration/Abstraction/BlogPostTestCase.php, tests/Integration/Abstraction/ContactListsTestCase.php, tests/Integration/Abstraction/CrmPipelinesTestCase.php, tests/Integration/Abstraction/DefaultTestCase.php, tests/Integration/Abstraction/EntityTestCase.php, tests/Integration/Abstraction/HubDBRowTestCase.php, tests/Integration/Abstraction/TimelineTestCase.php, tests/Integration/Abstraction/TimelineWithProprtyTestCase.php, tests/Integration/Resources/BlogCommentsTest.php, tests/Integration/Resources/CalendarEventsTest.php, tests/Integration/Resources/CompaniesTest.php, tests/Integration/Resources/ContactDinamicListsTest.php, tests/Integration/Resources/EmailEventsTest.php, tests/Integration/Resources/EmailSubscriptionTest.php, tests/Integration/Resources/EngagementsTest.php, tests/Integration/Resources/EventsTest.php, tests/Integration/Resources/HubDBRowTest.php, tests/Integration/Resources/IntegrationTest.php, tests/Integration/Resources/KeywordsTest.php, tests/Integration/Resources/LineItemsTest.php, tests/Integration/Resources/ObjectPropertiesTest.php, tests/Integration/Resources/ObjectPropertyGroupsTest.php, tests/Integration/Resources/OwnersTest.php, tests/unit/Exception/HubspotExceptionTest.php, tests/unit/Support/QueryBuilderTest.php, tests/unit/Utils/OAuth2Test.php, tests/unit/Utils/WebhooksTest.php
updates 
- upgrade  phpunit.xml from 5.0 to the latest version (9.5.10)
- change parent class PHPUnit_Framework_TestCase to TestCase
- Type hinting
=> update php unit tests

CHANGELOG.md, composer.json
https://github.com/HubSpot/hubspot-php/issues/383
https://github.com/HubSpot/hubspot-php/issues/382
=> bump version 4.0.2

src/Exceptions/HubspotException.php, src/Http/Client.php
https://github.com/HubSpot/hubspot-php/issues/143
=> Update Working with Errors

src/Endpoints/Files.php
fix points from https://github.com/HubSpot/hubspot-php/pull/389
https://github.com/HubSpot/hubspot-php/issues/120
=> fix Files Endpoint

composer.json
https://github.com/HubSpot/hubspot-php/issues/408
=> Lock psr/http-message to version v1.1.

README.md, src/Factory.php
=> Factory::createWithtoken announced deprecated and Remove hapikey from Readme
